#pragma once

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define DESIGN_WIDTH 512
#define DESIGN_HEIGHT 288

#define BACKGROUND_SCROLL_SPEED 30
#define BACKGROUND_LOOP_POINT 413
#define GROUND_SCROLL_SPEED 60
#define GROUND_LOOP_POINT 413

#define GRAVITY 10
#define JUMP_VELOCITY 5

#define PIPE_SCROLL (-GROUND_SCROLL_SPEED)
#define PIPE_SPAWN_DELAY_S 2
#define PIPE_SPACING 75
